global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'mev-engine'
    static_configs:
      - targets: ['host.docker.internal:9090']
    scrape_interval: 5s

  - job_name: 'cexdex'
    static_configs:
      - targets: ['host.docker.internal:9092']
    scrape_interval: 5s
